// Generated by gencpp from file fetch_images/GetImagesRequest.msg
// DO NOT EDIT!


#ifndef FETCH_IMAGES_MESSAGE_GETIMAGESREQUEST_H
#define FETCH_IMAGES_MESSAGE_GETIMAGESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fetch_images
{
template <class ContainerAllocator>
struct GetImagesRequest_
{
  typedef GetImagesRequest_<ContainerAllocator> Type;

  GetImagesRequest_()
    {
    }
  GetImagesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fetch_images::GetImagesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fetch_images::GetImagesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetImagesRequest_

typedef ::fetch_images::GetImagesRequest_<std::allocator<void> > GetImagesRequest;

typedef boost::shared_ptr< ::fetch_images::GetImagesRequest > GetImagesRequestPtr;
typedef boost::shared_ptr< ::fetch_images::GetImagesRequest const> GetImagesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fetch_images::GetImagesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fetch_images::GetImagesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fetch_images

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fetch_images::GetImagesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fetch_images::GetImagesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fetch_images::GetImagesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fetch_images::GetImagesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fetch_images/GetImagesRequest";
  }

  static const char* value(const ::fetch_images::GetImagesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::fetch_images::GetImagesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetImagesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fetch_images::GetImagesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fetch_images::GetImagesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FETCH_IMAGES_MESSAGE_GETIMAGESREQUEST_H
