// Generated by gencpp from file fetch_images/GetImages.msg
// DO NOT EDIT!


#ifndef FETCH_IMAGES_MESSAGE_GETIMAGES_H
#define FETCH_IMAGES_MESSAGE_GETIMAGES_H

#include <ros/service_traits.h>


#include <fetch_images/GetImagesRequest.h>
#include <fetch_images/GetImagesResponse.h>


namespace fetch_images
{

struct GetImages
{

typedef GetImagesRequest Request;
typedef GetImagesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetImages
} // namespace fetch_images


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fetch_images::GetImages > {
  static const char* value()
  {
    return "33cb5836216cc2f10faa186b171cbfdc";
  }

  static const char* value(const ::fetch_images::GetImages&) { return value(); }
};

template<>
struct DataType< ::fetch_images::GetImages > {
  static const char* value()
  {
    return "fetch_images/GetImages";
  }

  static const char* value(const ::fetch_images::GetImages&) { return value(); }
};


// service_traits::MD5Sum< ::fetch_images::GetImagesRequest> should match
// service_traits::MD5Sum< ::fetch_images::GetImages >
template<>
struct MD5Sum< ::fetch_images::GetImagesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_images::GetImages >::value();
  }
  static const char* value(const ::fetch_images::GetImagesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_images::GetImagesRequest> should match
// service_traits::DataType< ::fetch_images::GetImages >
template<>
struct DataType< ::fetch_images::GetImagesRequest>
{
  static const char* value()
  {
    return DataType< ::fetch_images::GetImages >::value();
  }
  static const char* value(const ::fetch_images::GetImagesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fetch_images::GetImagesResponse> should match
// service_traits::MD5Sum< ::fetch_images::GetImages >
template<>
struct MD5Sum< ::fetch_images::GetImagesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fetch_images::GetImages >::value();
  }
  static const char* value(const ::fetch_images::GetImagesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fetch_images::GetImagesResponse> should match
// service_traits::DataType< ::fetch_images::GetImages >
template<>
struct DataType< ::fetch_images::GetImagesResponse>
{
  static const char* value()
  {
    return DataType< ::fetch_images::GetImages >::value();
  }
  static const char* value(const ::fetch_images::GetImagesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FETCH_IMAGES_MESSAGE_GETIMAGES_H
